### ISSUE TITLE
ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 1 \r\n',))

### ISSUE THREAD

**Issue by sporebat** [aarronc/hutton-helper#65]
Not sure what's doing this:
```
event: CargoDepot
Traceback (most recent call last):
  File "C:\Users\garth\AppData\Local\EDMarketConnector\plugins\hutton-helper\xmit.py", line 46, in request
    response = getattr(requests, method)(url, timeout=DEFAULT_TIMEOUT, **kwargs)
  File "C:\Users\garth\Documents\source\hutton-helper\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\garth\Documents\source\hutton-helper\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\garth\Documents\source\hutton-helper\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\garth\Documents\source\hutton-helper\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\garth\Documents\source\hutton-helper\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 1 \r\n',))
```

**Comment by aarronc** [comment]
I cant reproduce this, do you have a timestamp so i can see what JSON went into the logs?
