### ISSUE TITLE
EDMC 5.0.0 and deleting registry keys

### ISSUE THREAD

**Issue by Athanasius** [aarronc/hutton-helper#79]
```python
2021-05-12 20:23:20.432 - INFO - 13176:18772:18772 plug.Plugin.__init__:49: loading plugin "HuttonHelperLite" from "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\load.py"
2021-05-12 20:23:20.455 - ERROR - 13176:18772:18772 plug.Plugin.__init__:64: : Failed for Plugin "HuttonHelperLite"
Traceback (most recent call last):
  File "plug.pyc", line 55, in __init__
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\load.py", line 84, in plugin_start3
    plugin_start(plugin_dir)
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\load.py", line 91, in plugin_start
    this.helper = plugin_module.HuttonHelperHelper(config, _refresh, _status)
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\plugin.py", line 100, in __init__
    self.prefs = HuttonHelperPreferences(config)
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\plugin.py", line 55, in __init__
    self.__config.delete(key)
  File "config.pyc", line 610, in delete
FileNotFoundError: [WinError 2] The system cannot find the file specified
2021-05-12 20:23:20.463 - ERROR - 13176:18772:18772 plug.load_plugins:161: Failure loading found Plugin "HuttonHelperLite"
Traceback (most recent call last):
  File "plug.pyc", line 159, in load_plugins
  File "plug.pyc", line 55, in __init__
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\load.py", line 84, in plugin_start3
    plugin_start(plugin_dir)
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\load.py", line 91, in plugin_start
    this.helper = plugin_module.HuttonHelperHelper(config, _refresh, _status)
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\plugin.py", line 100, in __init__
    self.prefs = HuttonHelperPreferences(config)
  File "C:\Users\Dlljs\AppData\Local\EDMarketConnector\plugins\HuttonHelperLite\plugin.py", line 55, in __init__
    self.__config.delete(key)
  File "config.pyc", line 610, in delete
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Basically with the new config code in 5.0.0 you'll need to pass `suppress=True` to `config.delete()` to avoid this when a key you're trying to delete didn't exist.  With that fix your plugin will get past this code and might work (depending on if there's anything else to fix).

**Comment by DlljsCodes** [comment]
Hi, I'm the user that reported this error.

**Comment by PsymonsB** [comment]
Thanks issuing a quick fix now to both lite and full version. the config.deletes() were there to delete some previous settings that are no longer used for now it won't matter if we dont delte them and we stoped using them along time ago so will only be users who have skipped multiple versions that will still have the rogue settings

**Comment by DlljsCodes** [comment]
Hutton Helper L1.0.6 confirmed working in EDMC 5.0.0
